### ISSUE TITLE
Can you add an example of the training data format

### ISSUE THREAD

**Issue by GeorgeDittmar** [lots-of-things/gpt2-bert-reddit-bot#4]
Hey I was curious if it might be possible to get added to the readme and example of the training data format. I know its comment [SEP] reply but I was curious if there was use of the <|endoftext|> token as well in the dataset format or not so gpt2 can know when an example ends.

Thanks!

**Comment by stedn** [comment]
Sure, I can add that to the readme.  Will do in the next couple of days.  Just so you know the `<|endoftext|>` token is appended to the end of each line in the data file so you don't have to add it..

**Comment by stedn** [comment]
Updated, hope that helps.
